### ISSUE TITLE
Mojave compatibility

### ISSUE THREAD

**Issue by rope** [iKenndac/Couch-Slouch#4]
I've just got USB-CEC Adapter by Pulse-Eight today and it doesn't work for me on Mojave (10.14).
When I change this line, it helps recognizing CEC and Mac can turn off TV, but apps do not respond to TVs RC commands:
https://github.com/Pulse-Eight/libcec/pull/434

**Comment by mrwagga** [comment]
How do you change that line? I can't figure it out...

**Comment by baebjr** [comment]
There is a new release 4.0.3 which solves the issue with Majoave

**Comment by WillDoy** [comment]
Will a new couch slouch build be available for download? I am non technical and was hoping someone could provide me with some guidance to get Couch Clouch in Mojave working again!

**Comment by mikrohard** [comment]
I could share my version. But I'm not sure if @iKenndac would agree with this.

**Comment by baebjr** [comment]
Why wouldn't he? It's a public open source project :-)

**Comment by iKenndac** [comment]
Full Mojave compatibility is a reasonably large amount of work — more than just the libCEC update. Mojave has much stronger security around scripting and control of other apps, which some features of Couch Slouch require to work properly (more info about this is [here](https://www.felix-schwarz.org/blog/2018/06/apple-event-sandboxing-in-macos-mojave)).

Also, parts of the UI are looking rather dated and it doesn't support high DPI displays correctly, so that needs a refresh too.

Since Couch Slouch earns close to zero money, it's hard to prioritise, but I hope to get to it over the Christmas/New Year break. Until then, if you've managed to put together something that works for you, feel free to share it around.

**Comment by mikrohard** [comment]
I only patched libcec to get adapter detection working... everything else works like before (at least the functionality I'm using).

You can get the compiled version here (edit: link removed).

**Comment by WillDoy** [comment]
Thank you very much @mikrohard  :) I will test this weekend and let you know!

**Comment by WillDoy** [comment]
@iKenndac I look forward to your new build after Christmas! It would be amazing to be able to change tv volume with the keyboard :)

**Comment by mrwagga** [comment]
Thanks mikrohard! All I use couch slouch and pulse eight for is to turn on/off my TV through homekit scenes. And your patch works great for that!

**Comment by WillDoy** [comment]
@mrwagga How do you control couch slouch with homekit scenes?

**Comment by mrwagga** [comment]
Homebridge + applescript

**Comment by WillDoy** [comment]
Ok I was wondering if it was Homebridge - thanks!

**Comment by iKenndac** [comment]
I just released Couch Slouch 1.0 (final - no more beta!) which includes proper Mojave support:

- Dark mode. 
- New high-res artwork for high DPI displays.
- Couch Slouch is now aware of Mojave's tighter accessibility access and will warn you if it doesn't have permission to control the system. 
- libCEC 4.0.4, which includes a number of bug fixes, including being able to detect devices in Mojave. 

If you're using the manually patched version, I recommend going back to the official release from http://couch-slouch.com. The patch might have broken Couch Slouch's code signature, which might then have broken the updater.

**Comment by iKenndac** [comment]
…and of course, thank you to @mikrohard for providing a solution while I found the free time to do all this. It's much appreciated!

**Comment by mikrohard** [comment]
New version works like a charm. Thanks for your work.

**Comment by WillDoy** [comment]
@iKenndac Thank you very much! Works great :) Any chance you could add TV volume control in the future? It would be great to control this from the keyboard.

Thanks again, much appreciate your efforts!!
