### ISSUE TITLE
Mac is "not" active TV source on startup

### ISSUE THREAD

**Issue by hepcat72** [iKenndac/Couch-Slouch#7]
So I've had Clouch-Slouch installed for awhile, but I didn't have a CEC adapter until now.  I got one for Christmas and just hooked it up.  After connecting, I launched Couch Slouch and it said that the Mac wasn't the active TV source (though I was viewing that message on the TV).  I tried rebooting the mac and got the same message.  Once I switched the HDMI source to a different HDMI port and back though, the icon turned from yellow to green and said I *was* connected.  Is this a bug?

Also... sorry for the noob questions, but:

I tried using the virtual remote, but none of the buttons seem to do anything.

The other thing is the the adapter came with no instructions.  It has a USB connection.  I connected that to a USB port on my computer, but I don't know if that's necessary.

I've been using the cec-lib install on my raspberry Pi to turn on/off (or rather sleep) the TV and switch HDMI inputs through HDMI 1, so I know sending instructions is possible, but it's pretty slow and I was hoping to see if I could do this via couch slouch from the Mac any faster.

I also would like to learn how to program it so that buttons on the TV remote do specific things on the computer.

So I have a few questions:

1. Does the cec adapter's USB need to be connected to a power source or the computer itself or at all? (I'm short on USB ports and right now, I have the keyboard/mouse unplugged so I can have the adapter plugged in - I don't really use the USB keyboard anyway, but it's nice as a backup)
2. Do I need a driver for the CEC adapter?
3. Should the virtual remote buttons be able to do anything out of the box (like turn on/off the TV)?
4. How do I send an instruction from the computer to the TV to switch HDMI inputs and/or turn on/off(/sleep) the TV?

These are all of course noob questions, so perhaps directing me to documentation is what I need?

**Comment by iKenndac** [comment]
Hello,

1. Yes, USB is how the computer communicates with the CEC adapter. Without a USB connection, the CEC adapter will do nothing.

2. No.

3. The virtual remote simulates you pushing buttons on your own TV's remote, so what it does depends on how it's configured. You can configure remote buttons in Couch Slouch's "Key Bindings" section.

4. You can configure some behaviours, like the TV being turned on with your Mac etc, in the "Behaviours" section of the app.
